// packages/shared/react-ui/src/components/layout/Footer.tsx
import React from 'react';

export interface FooterProps {
  colors: {
    text: string;
    border: string;
    bg: string;
    hover: string;
  },
  socials: Record<string, string>[]
}
// text-pop-secondary border-pop-secondary bg-dull-secondary/40
const Footer = ({
  colors,
  socials
}: FooterProps) => {
  return (
    <div className={`px-4 py-4 md:py-6 md:flex md:items-center md:justify-between border-t-0 ${colors.text} ${colors.border} ${colors.bg}`}>
      <div className="flex justify-center space-x-6 md:order-2">
        {socials.map((item, index) => (
          <a
            key={index}
            href={item.href}
            target="_blank"
            className={`hover:${colors.hover}`}
          >
            <div className="sr-only fixed">{item.name}</div>
            <div className={item.icon}></div>
          </a>
        ))}
      </div>

      <div className="md:order-1 mt-4 md:mt-0">
        <div className="text-center text-sm leading-5">
          <i className="fa-regular fa-copyright"></i> 2024 - Present. All rights
          reserved.
        </div>
      </div>
    </div>
  );
};

export default Footer;

// src/components/layout/Footer.vue
<template>
  <footer>
    <div
      class="px-4 py-8 md:flex md:items-center md:justify-between text-pop-primary"
    >
      <div class="flex justify-center space-x-6 md:order-2">
        <a
          v-for="item in socials"
          :key="item.name"
          :href="item.href"
          class="hover:text-pop-secondary"
          target="_blank"
        >
          <span class="sr-only">{{ item.name }}</span>
          <span :class="item.icon"></span>
        </a>
      </div>

      <div class="md:order-1 mt-5 md:mt-0">
        <p class="text-center text-xs leading-5">
          <i class="fa-regular fa-copyright"></i> 2024 - Present. All rights
          reserved.
        </p>
      </div>
    </div>
  </footer>
</template>

<script setup>
// https://fontawesome.com/search
const socials = [
  {
    name: "website",
    href: "https://wearesam.co",
    icon: "fa-solid fa-globe",
  },
  {
    name: "GitHub",
    href: "https://github.com/wearesamco????",
    icon: "fa-brands fa-github",
  },
  {
    name: "LinkedIn",
    href: "https://www.linkedin.com/company/wearesamco/",
    icon: "fa-brands fa-linkedin",
  },
  {
    name: "X",
    href: "https://x.com/XXXXX",
    icon: "fa-brands fa-twitter",
  },
  {
    name: "Instagram",
    href: "https://instagram.com/XXXXX",
    icon: "fa-brands fa-instagram",
  },
  // {
  //   name: "facebook",
  //   href: "https://discord.gg/XXXXXX",
  //   icon: "fa-brands fa-facebook",
  // },
  // {
  //   name: "Discord",
  //   href: "https://discord.gg/XXXXXX",
  //   icon: "fa-brands fa-discord",
  // },
  // {
  //   name: "YouTube",
  //   href: "https://www.youtube.com/XXXXX",
  //   icon: "fa-brands fa-youtube",
  // },
];
</script>
