// packages/clients/anti-social-network/src/components/landing/TopNavigation.tsx
import { Link, useLocation } from 'react-router-dom';
import { landing_page_navigation } from '@/helpers/navigation';
import { BaseButton } from '@am-ogs/react-ui';

// import ThemeToggle from "@/components/ThemeToggle";

const TopNavigation = () => {
  const location = useLocation();
  const { pathname } = location;

  const login =() => {

  }
  return (
    <div className="flex flex-row px-8 py-2 items-center justify-between border-b shadow-md bg-dull-primary">
      {/* Logo */}
      <div className="flex">
        <Link to="/">
          <img
            src="/3.png"
            alt="logo"
            className="p-2 h-14 object-cover"
          />
        </Link>
        {pathname === '/at-home' && (
          <img
            src="/5.png"
            alt="logo"
            className="p-2 h-14 object-cover border-l-2"
          />
        )}
      </div>

      {/* Navigation Links (Hidden on Small Screens) */}
      <nav className="hidden md:flex space-x-10 text-pop-secondary font-medium">
        {landing_page_navigation.map((page, index) => (
          <div
            key={index}
            className="text-pop-secondary hover:text-pop-primary transition text-sm"
          >
            <Link to={`/${page.action}`}>{page.name}</Link>
          </div>
        ))}

        {/* <ThemeToggle className="ml-24" /> */}
      </nav>

      {/* <BaseButton text="Start Your Return" handler={login} /> */}
    </div>
  );
};

export default TopNavigation;

// packages/apps/my-portfolio/src/components/landing/TopNavigation.vue
<template>
  <!-- Navigation Bar -->
  <nav
    class="flex w-full p-2 items-center justify-between border-b border-pop-secondary shadow-lg"
  >
    <!-- Logo -->
    <div class="flex items-center">
      <img
        src="/7.png"
        alt="logo"
        class="w-16 h-16 object-cover rounded-full"
      />
    </div>

    <div class="flex space-x-8 pt-6 text-pop-secondary font-medium">
      <div
        v-for="item in landing_page_navigation"
        :key="item.action"
        class="flex"
      >
        <a
          href="#"
          @click="emitAction(item.action)"
          class="hover:text-pop-primary transition"
        >
          {{ item.name }}
        </a>
      </div>

      <ThemeToggle />
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ThemeToggle } from "@am-ogs/vue-ui";
import { Events, landing_page_navigation } from "@/helpers";

const emit = defineEmits([Events.SCROLL_TO]);
const emitAction = (value: string) => {
  console.log("emiting", value);
  emit(Events.SCROLL_TO, value);
};
</script>
