// packages/clients-projects/teen-hustle-website/src/components/TopNavigation.tsx
import { Link, useLocation } from 'react-router-dom';
import { landing_page_navigation } from '@/helpers/navigation';

const TopNavigation = () => {
  const location = useLocation();
  const { pathname } = location;

  const login = () => {};
  return (
    <div className="flex flex-row px-4 items-center justify-between border-b bg-dull-primary">
      {/* Logo */}
      <div className="flex">
        <Link to="/">
          <img
            src="/circle-lockers-rows-sm.png"
            alt="logo"
            className="h-14 md:h-20 object-cover"
          />
        </Link>
        {pathname === '/partners' && (
          <img
            src="/logo-teen-hustl.png"
            alt="logo"
            className="h-14 md:h-20 ml-2 pb-[.1rem] pt-3 pl-3 object-cover border-l-2"
          />
        )}
      </div>

      {/* Navigation Links (Hidden on Small Screens) */}
      <nav className="hidden md:flex space-x-6 lg:space-x-12 mt-auto mb-1 text-pop-secondary font-medium">
        {landing_page_navigation.map((page, index) => (
          <div
            key={index}
            className="text-pop-secondary hover:text-pop-primary transition text-sm"
          >
            <Link to={`/${page.action}`}>{page.name}</Link>
          </div>
        ))}

        {/* <ThemeToggle className="ml-24" /> */}
      </nav>

      {/* <BaseButton text="Start Your Return" handler={login} /> */}
    </div>
  );
};

export default TopNavigation;

// packages/apps/my-briefcase/src/components/landing/TopNavigation.vue
<template>
  <!-- Navigation Bar -->
  <nav
    :class="[
      'flex w-full',
      'bg-dull-primary',
      'items-center justify-between',
      'border-b border-pop-secondary shadow-lg',
    ]"
  >
    <!-- Logo -->
    <div class="flex ml-2 h-16 items-center">
      <img src="/landing.png" alt="logo" class="w-12 md:w-16 object-cover" />
    </div>

    <!-- Navigation Links (Hidden on Small Screens) -->
    <div
      class="hidden md:flex space-x-4 md:space-x-8 pt-8 pb-3 text-pop-secondary font-medium"
    >
      <div v-for="item in landing_page_navigation" :key="item.name">
        <a
          href="#"
          @click="emitAction(item.action)"
          class="hover:text-pop-primary transition"
        >
          {{ item.name }}
        </a>
      </div>

      <ThemeToggle />
    </div>

    <LoginButton />
  </nav>
</template>

<script setup lang="ts">
import { ThemeToggle } from '@am-ogs/vue-ui';
import { Events, landing_page_navigation } from '@/helpers';
import LoginButton from '@/components/identity/LoginButton.vue';

const emit = defineEmits([Events.SCROLL_TO]);
const emitAction = (value: string) => {
  console.log('emiting', value);
  emit(Events.SCROLL_TO, value);
};
</script>
