// src/components/layout/widget/ColumnLayout.vue
<template>
  <div class="flex justify-center items-center">
    <div class="grid grid-cols-1 md:grid-cols-5 gap-10 items-center">
      <!-- Left Content -->
      <div class="col-span-1 md:col-span-3">
        <div class="space-y-2 md:space-y-4">
          <h1
            class="text-4xl md:text-6xl font-bold text-pop-secondary leading-tight"
          >
            <slot name="title" />
          </h1>

          <div class="flex space-x-12 text-pop-primary">
            <slot name="subTitle" />
          </div>

          <p class="text-lg md:text-2xl text-secondary/50">
            <slot name="description" />
          </p>
        </div>

        <div>
          <slot name="leftContent" />
        </div>
      </div>

      <!-- Right Image -->
      <div class="col-span-1 md:col-span-2">
        <slot name="rightContent" />
      </div>
    </div>
  </div>
</template>

// packages/libs/react-ui/src/components/layout/ColumnLayout.tsx
import React from 'react';

export interface ColumnLayoutProps {
  title?: string;
  subTitle?: React.ReactNode | string;
  description?: React.ReactNode | string;
  leftContent?: React.ReactNode;
  rightContent?: React.ReactNode;
}

const ColumnLayout = ({
  title,
  subTitle,
  description,
  leftContent,
  rightContent,
}: ColumnLayoutProps) => {
  return (
    <div className="flex justify-center items-center">
      <div className="grid grid-cols-1 md:grid-cols-5 gap-10 items-center">
        {/* Left Content */}
        <div className="col-span-1 md:col-span-3">
          <div className="text-3xl md:text-5xl font-bold text-pop-secondary leading-tight">
            {title}
          </div>
          <div className="flex space-x-12 text-pop-primary">{subTitle}</div>
          <div className="text-dull-secondary/50">
            {description}
          </div>
          <div>{leftContent}</div>
        </div>

        {/* Right Image */}
        <div className="col-span-1 md:col-span-2">{rightContent}</div>
      </div>
    </div>
  );
};

export default ColumnLayout;
