// src/components/layout/PageLayout.vue
<template>
  <main class="flex-1 not-italic">
    <div class="relative mx-auto">
      <div class="pb-16 pt-10">
        <!-- Page Titles -->
        <div class="px-4 sm:px-6 lg:px-0">
          <h1 class="text-3xl font-bold tracking-tight text-pop-secondary">
            <slot name="pageTitle" />
          </h1>
          <p class="max-w-2xl text-sm text-secondary pt-2 italic">
            <slot name="description" />
          </p>
        </div>
        <!-- End Page Titles -->

        <div class="px-4 sm:px-6 lg:px-0">
          <div class="py-6">
            <slot name="tabs" />
            <slot name="search" />
            <slot name="pageContent" />
          </div>
        </div>
      </div>
    </div>
  </main>
</template>

// packages/shared/react-ui/src/components/layout/PageLayout.tsx
import React from 'react';

export interface PageLayoutProps {
  pageTitle: string;
  description: string;
  tabs: React.ReactNode;
  search: React.ReactNode;
  pageContent: React.ReactNode;
}

const PageLayout = ({
  pageTitle,
  description,
  tabs,
  search,
  pageContent,
}: PageLayoutProps) => {
  return (
    <main className="flex-1 not-italic">
      <div className="relative mx-auto">
        <div className="pb-16 pt-10">
          {/* Page Titles */}
          <div className="px-4 sm:px-6 lg:px-0">
            <h1 className="text-3xl font-bold tracking-tight text-pop-secondary">
              {pageTitle}
            </h1>
            <div className="max-w-2xl text-sm text-dull-secondary pt-2">
              {description}
            </div>
          </div>
          {/* End Page Titles */}

          <div className="px-4 sm:px-6 lg:px-0">
            <div className="py-6">
              {tabs}
              {search}
              {pageContent}
            </div>
          </div>
        </div>
      </div>
    </main>
  );
};

export default PageLayout;
