// packages/client/src/components/experimental/SiteLayout.vue
<template>
  <div id="ogs-site-layout">
    <!-- the X value needs to match b/w the lg:w-X of the side column and the lg:pl-X of the main column -->

    <!-- Left Column -->
    <div
      id="ogs-sl-side-menu"
      v-if="is_authenticated"
      class="hidden lg:fixed lg:flex lg:flex-col lg:inset-y-0 lg:z-50 lg:w-80"
    >
      <slot name="sideMenu" />
    </div>

    <!-- Main Column  -->
    <div
      id="ogs-sl-main-column"
      :class="[
        is_authenticated ? 'lg:pl-80' : '',
        'flex flex-col h-screen justify-between',
      ]"
    >
      <div
        v-if="is_authenticated"
        id="ogs-sl-header-authenticated"
        class="sticky top-0 z-40 lg:px-8"
      >
        <slot name="header" />
      </div>
      <div
        v-else
        id="ogs-sl-top-nav-public"
        class="sticky top-0 z-40 sm:px-6 lg:px-36"
      >
        <slot name="topNavigation" />
      </div>

      <main
        id="ogs-sl-main"
        class="mb-auto mx-auto w-full py-4 px-4 sm:px-6 lg:px-24 overflow-auto scrollbar"
      >
        <slot name="toast" />
        <slot name="routerView" />
      </main>

      <div id="ogs-sl-footer" class="sticky z-40 mx-4">
        <slot name="footer" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  is_authenticated: Boolean;
}>();
</script>

// packages/shared/react-ui/src/components/layout/SiteLayout.tsx
import React from 'react';

export interface SiteLayoutProps {
  isLoading?: boolean;
  isAuthenticated: boolean;
  sideMenu?: React.ReactNode;
  header?: React.ReactNode;
  topNavigation?: React.ReactNode;
  appRoutes?: React.ReactNode;
  footer?: React.ReactNode;
}
const SiteLayout = ({
  isLoading,
  isAuthenticated,
  sideMenu,
  header,
  topNavigation,
  appRoutes,
  footer,
}: SiteLayoutProps) => {
  return (
    <div>
      {/* the X value needs to match b/w the lg:w-X of the side column and the lg:pl-X of the main column  */}

      {/* Left Column  */}
      {isAuthenticated && (
        <div className="hidden lg:fixed lg:flex lg:flex-col lg:inset-y-0 lg:z-50 lg:w-80">
          {sideMenu}
        </div>
      )}

      {/* Main Column   */}
      <div
        className={`flex flex-col h-screen justify-between ${isAuthenticated ? 'lg:pl-80' : ''}`}
      >
        {isAuthenticated && (
          <div className="sticky top-0 z-40 lg:px-8">{header}</div>
        )}

        {!isAuthenticated && (
          <header className="sticky top-0 z-40">
            {topNavigation}
          </header>
        )}

        <main className="grow w-full mt-4 p-4 sm:px-6 lg:px-44 scrollbar overflow-auto ">
          {!isLoading && <div>{appRoutes}</div>}
        </main>

        <footer className="sticky bottom-0 z-40">{footer}</footer>
      </div>
    </div>
  );
};

export default SiteLayout;
